const phrasesFile = [
"Idle hands are the devil's workshop; idle lips are his mouthpiece<br>Proverbs 16:27-29",
"Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth<br><b>Marcus Aurelius</b>",
"Dwell on the beauty of life. Watch the stars, and see yourself running with them<br><b>Marcus Aurelius</b>",
"It is not death that a man should fear, but he should fear never beginning to live<br><b>Marcus Aurelius</b>",
"Whenever you are about to find fault with someone, ask yourself the following question: What fault of mine most nearly resembles the one I am about to criticize<br><b>Marcus Aurelius</b>",
"How much more grievous are the consequences of anger than the causes of it<br><b>Marcus Aurelius</b>",
"Live a good life. If there are gods and they are just, then they will not care how devout you have been, but will welcome you based on the virtues you have lived by. If there are gods, but unjust, then you should not want to worship them. If there are no gods, then you will be gone, but will have lived a noble life that will live on in the memories of your loved ones<br><b>Marcus Aurelius</b>",
"Though you break your heart, men will go on as before<br><b>Marcus Aurelius</b>",
"Nowhere can man find a quieter or more untroubled retreat than in his own soul<br><b>Marcus Aurelius</b>",
"The things you think about determine the quality of your mind<br><b>Marcus Aurelius</b>",
"Life is opinion<br><b>Marcus Aurelius</b>",
"The honest and good man ought to be exactly like a man who smells strong, so that the bystander as soon as he comes near him must smell wheteher he choose or not<br><b>Marcus Aurelius</b>",
"Ad astra per aspera",
"Learn how to live and you'll know how to die<br><b>Morrie Schwartz</b>",
"Be tolerant with others and strict with yourself<br><b>Marcus Aurelius</b>",
"Accustom yourself not to be disregarding of what someone else has to say: as far as possible enter into the mind of the speaker<br><b>Marcus Aurelius</b>",
"Whatever time you choose is the right time. Not late, not early<br><b>Marcus Aurelius</b>",
"Frightened of change? But what can exist without it? What's closer to nature's heart? Can you take a hot bath and leave the firewood as it was? Eat food without transforming it? Can any vital process take place without something being changed? Can't you see? It's just the same with you, and just as vital to nature<br><b>Marcus Aurelius</b>",
"The universe is change, and life mere opinion<br><b>Marcus Aurelius</b>",
"Give your heart to the trade you have learnt, and draw refreshment from it<br><b>Marcus Aurelius</b>",
"To be like the rock that the waves keep crashing over. It stands unmoved and the raging of the sea falls still around it<br><b>Marcus Aurelius</b>",
"In everything that you do, pause and ask yourself if death is a dreadful thing because it deprives you of this<br><b>Marcus Aurelius</b>",
"A good man does not spy around for the black spots in others, but presses unswervingly on towards his mark<br><b>Marcus Aurelius</b>",
"Wealth consists not in having great possessions, but in having few wants<br><b>Epictetus</b>",
"Don't explain your philosophy. Embody it.<br><b>Epictetus</b>",
"Other people's views and troubles can be contagious. Don't sabotage yourself by unwittingly adopting negative, unproductive attitudes through your associations with others.<br><b>Epictetus</b>",
"Nature hath given men one tongue but two ears, that we may hear from others twice as much as we speak<br><b>Epictetus</b>",
"No man is free who is not master of himself<br><b>Epictetus</b>",
"The greater the difficulty, the more glory in surmounting it. Skillful pilots gain their reputation from storms and tempests<br><b>Epictetus</b>",
"No great thing is created suddenly<br><b>Epictetus</b>",
"It is unrealistic to expect people to see you as you see yourself<br><b>Epictetus</b>",
"There is no shame in making an honest effort<br><b>Epictetus</b>",
"The more we value things outside our control, the less control we have<br><b>Epictetus</b>",
"No one is ever unhappy because of someone else<br><b>Epictetus</b>",
"Tell yourself what you want to be, then act your part accordingly<br><b>Epictetus</b>",
"Let silence be your general rule; or say only what is necessary and in few words<br><b>Epictetus</b>",
"We should realize that an opinion is not easily formed unless a person says and hears the same things every day and practises them in real life<br><b>Epictetus</b>",
"Associate with people who are likely to improve you<br><b>Lucius Annaeus Seneca</b>",
"Wealth is the slave of a wise man. The master of a fool<br><b>Lucius Annaeus Seneca</b>",
"Our plans miscarry because they have no aim. When a man does not know what harbor he is making for, no wind is the right wind.<br><b>Lucius Annaeus Seneca</b>",
"Fate leads the willing and drags along the reluctant<br><b>Lucius Annaeus Seneca</b>",
"The mind that is anxious about future events is miserable<br><b>Lucius Annaeus Seneca</b>",
"What man can you show me who places any value on his time, who reckons the worth of each day, who understands that he is dying daily? For we are mistaken when we look forward to death. The major portion of death has already passed. Whatever years be behind us are in death's hands<br><b>Lucius Annaeus Seneca</b>",
"It is of course better to know useless things than to know nothing<br><b>Lucius Annaeus Seneca</b>",
"It's not that we have little time, but more that we waste a good deal of it<br><b>Lucius Annaeus Seneca</b>",
"It is a great thing to know the season for speech and the season for silence<br><b>Lucius Annaeus Seneca</b>",
"So it is: we are not given a short life but we make it short, and we are not ill, suplied but wasteful of it<br><b>Lucius Annaeus Seneca</b>",
"All things that are still to come lie in uncertainty; live straightway!<br><b>Lucius Annaeus Seneca</b>",
"Envy of other people shows how they are unhappy. Their continual attention to others behavior shows how they are boring<br><b>Lucius Annaeus Seneca</b>",
"If you accomplish something good with hard work, the labor passes quickly but the good endures; if you do something shameful in pursuit of pleasure, the pleasure passes quickly, but the shame endures<br><b>Gaius Musonius Rufus</b>",
"That which exercises reason is more excellent than that which does not exercise reason; there is nothing more excellent than the universe, therefore the universe exercises reason<br><b>Zeno of Citium</b>",
"question = ( to ) ? be : ! be<br><b>William Shakespeare</b>",
"God is a comedian playing to an audience too afraid to laugh<br><b>Voltaire</b>",
"Perhaps the most valuable result of all education is the ability to make yourself do the thing you have to do, when it ought to be done, whether you like it or not<br><b>Thomas Henry Huxley</b>",
"Success is liking yourself, liking what you do, and liking how you do it<br><b>Maya Angelou</b>",
"It's not a 9-5 job. It's an every moment you're awake job because you actually enjoy the work that you're doing.<br><b>Jeffrey Kalmikoff</b>",
"There are two tragedies in life. One is not to get your heart's desire. The other is to get it.<br><b>George Bernard Shaw</b>",
"He who hesitates is a damned fool.<br><b>Mae West</b>",
"Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like.<br><b>Lao Tzu</b>",
"You are scrupulously honest, frank, and straightforward. Therefore you have few friends.",
"I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living, It's a way of looking at life through the wrong end of a telescope. Which is what I do, And that enables you to laugh at life's realities.<br><b>Dr. Seuss</b>",
"Take the attitude of a student, never be too big to ask questions, never know too much to learn something new.<br><b>Og Mandino</b>",
"In a world where there is so much to be done. I felt strongly impressed that there must be something for me to do.<br><b>Dorothea Dix</b>",
"The fragrance always remains in the hand that gives the rose.<br><b>Heda Bejar</b>",
"Democracy is the worst form of government, except for all the others.<br><b>Winston S. Churchill</b>",
"Responsibility is the price of greatness.<br><b>Winston S. Churchill</b>",
"What you risk reveals what you value.<br><b>Jeanette Winterson</b>",
"Evil exists, but not without good, like shadow exists, but not without light.<br><b>Alfred de Musset</b>",
"I've found that I can always do the things that people do in books. Really they are the only things I can do.<br><b>F. Scott Fitzgerald</b>",
"Where all think alike, no one thinks very much.<br><b>Walter Lippmann</b>",
"Power is the ultimate aphrodisiac.<br><b>Chelsea G. Summers</b>",
"Pray that your loneliness may spur you into finding something to live for, great enough to die for.<br><b>Dag Hammarskjold</b>",
"Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.<br><b>Scott Adams</b>",
"Whatever you may be sure of, be sure of this-that you are dreadfully like other people.<br><b>James Russel Lowell</b>",
"Be the man your dog knows you to be.<br><b>Mike Overlie</b>",
"God rewards every act of obedience to His Will.<br><b>Jaachynma N.E. Agu</b>",
"You can't build a reputation on what you are going to do.<br><b>Henry Ford</b>",
"Happiness lies in the joy of achievement and the thrill of creative effort.<br><b>Franklin D. Roosevelt</b>",
"Normal is not something to aspire to, it's something to get away from.<br><b>Jodie Foster</b>",
"The object of life is not to be on the side of the masses, but to escape finding oneself in the ranks of the insane.<br><b>Marcus Aurelius</b>",
"The journey of a thousand miles must begin with a single step.<br><b>Lao Tzu</b>",
"Nothing is worth more than this day. You cannot relive yesterday. Tomorrow is still beyond your reach.<br><b>Johann Wolfgang von Goethe</b>",
"If you don't know where you are going, any road will get you there.<br><b>Lewis Carroll</b>",
"Today's weirdness is tomorrow's reason why.<br><b>Hunter S. Thompson</b>",
"When you're the first person whose beliefs are different from what everyone else believes, you're basically saying 'I'm right, and everybody else is wrong.' That's a very unpleasant position to be in. It's at once exhilarating and at the same time, an invitation to be attacked.<br><b>Larry Ellison</b>",
"Wealth is the ability to fully experience life.<br><b>Henry David Thoreau</b>",
"I'm a great believer in luck, and I find the harder I work, the more I have of it.<br><b>Thomas Jefferson</b>",
"By working faithfull 8 hours a day, you may eventually get to be the boss and work 12 hours a day.<br><b>Robert Frost</b>",
"The only thing that interferes with my learning is my education.<br><b>Albert Einstein</b>",
"There was a time when a fool and his money were soon parted, but now it happens to everybody.<br><b>Adlai Stevenson</b>",
"I'd rather live in regret of failure than in regret of never trying.<br><b>MJ DeMarco</b>",
"People would do better, if they knew better.<br><b>Jim Rohn</b>",
"It ain't what you don't know that gets you in trouble. It's what you know for sure that just ain't so.<br><b>Mark Twain</b>",
"Try not to become a man of success, but a man of value.<br><b>Albert Einstein</b>",
"Events and circumstances have their origin in ourselves. They spring from seeds which we have sown.<br><b>Henry David Thoreau</b>",
"Your life is the sum result of all the choices you make, both consciously and unconsciously. If you can control the process of choosing, you can take control of all aspects of your life. You can find the freedom that comes from being in charge of yourself.<br><b>Robert F. Bennett</b>",
"Until we see what we are, we cannot take steps to become what we should be.<br><b>Charlotte P. Gilman</b>",
"Ridicule is the tribute paid to the genius by the mediocrities.<br><b>Oscar Wilde</b>",
"He who chooses the beginning of the road chooses the place it leads to. It is the means that determines the end.<br><b>Henry Emerson Fosdick</b>",
"What do we live for, if not to make life less difficult for each other?<br><b>George Eliot</b>",
"You can't live a perfect day without doing something for someone who will never be able to repay you.<br><b>John Wooden</b>",
"At first, people refuse to believe that a strange new thing can be done, then they begin to hope it can be done, then they see it can be done-then it is done, and all the world wonders why it was not done centuries ago.<br><b>Frances Hodgson Burnett</b>",
"The tragedy of life doesn't lie in not reaching your goal. The tragedy lies in having no goal to reach.<br><b>Benjamin Mays</b>",
"No horse gets anywhere until he is harnessed. No steam or gas ever drives anything until it is confined. No Niagara is ever turned into light and power until it is tunneled. No life ever grows great until it is focused, dedicated, disciplined.<br><b>Harry Emerson Fosdick</b>",
"Your choices are made in a moment, but their consequences will transcend a lifetime.<br><b>MJ DeMarco</b>",
"I have always thought the actions of men the best interpreters of their thoughts.<br><b>John Locke</b>",
"My heart's been empty since you left - but still I refuse to put up a vacancy sign. I'm just not ready for anybody else to move in yet.<br><b>Ranata Suzuki</b>",
"I am looking for a lot of men who have an infinite capacity to not know what can't be done.<br><b>Henry Ford</b>",
"In the absences of a decent time machine, fiction remains the most sturdy vehicle for visiting other eras.<br><b>Tom Nolan</b>",
"As we grow old... the beauty steals inward.<br><b>Ralph Waldo Emerson</b>",
"She treads like a shadow and stalks like a dream... terribly close, but always out of reach.<br><b>Glenn Parris</b>",
"Sane and intelligent human beings are like all other human beings, and carefully and cautiously and diligently conceal their private real opinions from the world and give out fictitious ones in their stead for general consumption.<br><b>Mark Twain</b>",
"I think people that have a brother or sister don't realize how lucky they are. Sure, they fight a lot, but to know that there's always somebody there, somebody that's family.<br><b>Trey Parker and Matt Stone</b>",
"Why comes temptation, but for man to meet and master and crouch beneath his foot, and so be pedestaled in triumph?.<br><b>Robert Browning</b>",
"When you go to buy, use your eyes, not your ears.<br><b>Czech Proverb</b>",
"Don't forget, a person's greatest emotional need is to feel appreciated.<br><b>H. Jackson Brown Jr.</b>",
"Have you heard that it was good to gain the day? I also say it is good to fall, battles are lost in the same spirit in which they are won.<br><b>Walt Whitman</b>",
"For knowing and refusing to know.<br><b>Jennifer Nansubuga Makumbi</b>",
"It's always about timing. If it's too soon, no one understands. If it's too late, everyone's forgotten.<br><b>Anna Wintour</b>",
"Having a baby's sweet face so close to your own, for so long a time as it takes to nurse 'em, is a great tonic for a sad soul.<br><b>Erica Eisdorfer</b>",
"Maybe we forget so that we can go on.<br><b>John Green</b>",
"Faith and breath are inevitable for life.<br><b>Dido Stargaze</b>",
"For no soul can ever be replaced, and death claims a beauty and a magnificence that will always be missed.<br><b>Jocelyn Soriano</b>",
"One can't stay sad very long in such an interesting world, can one?<br><b>L. M. Montgomery</b>",
"What is called a reason for living is also an excellent reason for dying.<br><b>Albert Camus</b>",
"The average man, who does not know what to do with his life, wants another one which will last forever.<br><b>Anatole France</b>",
"Cynics regarded everybody as equally corrupt... Idealists regarded everybody as equally corrupt, except themselves.<br><b>Robert Anton Wilson</b>",
"Hardships make or break people.<br><b>Margaret Mitchell</b>",
"We have an opportunity for everyone in the world to have access to all the world's information. This has never before been possible. Why is ubiquitous information so profound? It's a tremendous equalizer. Information is power.<br><b>Eric Schmidt</b>",
"Great leaders don't allow failure to redefine their purpose- they use failure to refine their purpose.<br><b>Drenda Keesee</b>",
"The more you are able to forgive then the more you are able to love.<br><b>Stephen Richards</b>",
"When you initially forgive, it is like letting go of a hot iron. There is initial pain and the scars will show, but you can start living again.<br><b>Stephen Richards</b>",
"The time to relax is when you don't have time for it.<br><b>Sydney J. Harris</b>",
"The day you'll start craving for a savior to deliver you is the day you'll welcome any tyrant into your soul. Freedom is the game of the unsaved and the unsavable.<br><b>Giannis Delimitsos</b>",
"You can't just wish change; you have to live the change in order for it to become a reality.<br><b>Steve Maraboli</b>",
"Keep playing games. Make time to play games with your friends and family, because it's surprisingly heartbreaking to wipe a thin layer of dust off a game you love, before you put it back on the shelf because the real world is calling you.<br><b>Wil Wheaton</b>",
"The biggest risk is not in what you build. It is in not supporting what you build.<br><b>Jeffrey Shaw</b>",
"Build systems for the business to come, not the business you have.<br><b>Jeffrey Shaw</b>",
"Strive to be bored is a contradictory statement for most entrepreneurs. But we have to strive to be bored to make space for more if we want to grow our business.<br><b>Jeffrey Shaw</b>",
"Most of the change we think we see in life is due to truths being in and out of favor.<br><b>Robert Frost</b>",
"The truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, unless you realize that the situation is over, you cannot move forward.<br><b>Steve Maraboli</b>",
"Life becomes easier and more beautiful when we can see the good in other people.<br><b>Roy T. Bennett</b>",
"Nature is pleased with simplicity. And nature is no dummy.<br><b>Isaac Newton</b>",
"A bone to the dog is not charity. Charity is the bone shared with the dog, when you are just as hungry as the dog.<br><b>Jack London</b>",
"We live in a society exquisitely dependent on science and technology, in which hardly anyone knows anything about science and technology.<br><b>Carl Sagan</b>",
];
export default phrasesFile;
